ttvote/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from vote import views

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('vote/', include('vote.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import VoteView, DoneView, ResultView

app_name = "vote"

urlpatterns = [
    path('<int:id>/', VoteView.as_view(), name="vote"),
    path('<int:election>/<uuid:slug>/', DoneView.as_view(), name="vote_done"),
    path('<int:election>/results/', ResultView.as_view(), name="results")
]

vote/models.py
import uuid
from django.db import models


class Election(models.Model):
    name = models.CharField(max_length=30)
    max_votes = models.PositiveSmallIntegerField()
    active = models.BooleanField()
    intro = models.TextField(blank=True, help_text="The text to display at the top of the election. HTML enabled")

    def __str__(self):
        return self.name


class Option(models.Model):
    image = models.ImageField()
    text = models.CharField(max_length=50)
    election = models.ForeignKey(Election, on_delete=models.CASCADE)

    def formid(self):
        return "option_" + str(self.election.id) + "_" + str(self.id)

    def __str__(self):
        return self.text

    def votes(self):
        return self.vote_set.count()


# Create your models here.
class Vote(models.Model):
    ip = models.GenericIPAddressField(editable=False)
    uuid = models.UUIDField(editable=False, default=uuid.uuid4)
    election = models.ForeignKey(Election, on_delete=models.CASCADE)
    selections = models.ManyToManyField(Option)
    time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.uuid)

vote/views.py
import random

from django.db.models import Count
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, TemplateView, ListView, DetailView
from django.shortcuts import get_object_or_404, HttpResponseRedirect, reverse

from .models import Election, Vote, Option


class HomeView(ListView):
    template_name = "home.html"
    model = Election
    context_object_name = "elections"

    def get_queryset(self):
        return Election.objects.filter(active=True)


class DoneView(DetailView):
    model = Vote
    slug_field = "uuid"
    template_name = "done.html"

    def get_queryset(self):
        self.election = get_object_or_404(Election, id=self.kwargs['election'])
        return self.election.vote_set.all()


class ResultView(LoginRequiredMixin, ListView):
    model = Option
    template_name = "results.html"
    ordering = [Count("votes_set")]
    context_object_name = "choices"

    def get_queryset(self):
        self.election = get_object_or_404(Election, id=self.kwargs['election'])
        return self.election.option_set.all()

    def get_context_data(self, **kwargs):
        ctxt = super().get_context_data(**kwargs)
        self.election = get_object_or_404(Election, id=self.kwargs['election'])
        ctxt['election'] = self.election
        ctxt['choices'] = sorted(ctxt['choices'], key=lambda x: -x.votes())
        return ctxt


# Create your views here.
class VoteView(TemplateView):
    template_name = "votescreen.html"

    def post(self, request, **kwargs):
        self.get_context_data(**kwargs)
        print(request.POST)
        errors = []
        if "selection" not in request.POST:
            errors.append("Please select at least one option")
            selection = []
        else:
            selection = request.POST.getlist("selection")
        if 0 < self.election.max_votes < len(selection):
            errors.append("Too many options selected")
        try:
            selection = [int(s) for s in selection]
        except ValueError:
            errors.append("Invalid option submitted")
        for i in selection:
            allowed = [a.id for a in self.election.option_set.all()]
            if i not in allowed:
                errors.append("Unknown option selected")

        if errors:
            return self.get(request, errors=errors)
        else:
            vote = Vote(
                ip=request.META['REMOTE_ADDR'],
                election=self.election,
            )
            vote.save()
            vote.selections.add(*selection)
            return HttpResponseRedirect(
                reverse("vote:vote_done", kwargs={'election': self.election.id, 'slug': vote.uuid}))

    def get_context_data(self, **kwargs):
        ctxt = super().get_context_data(**kwargs)
        self.election = get_object_or_404(Election, id=self.kwargs['id'], active=True)
        ctxt['election'] = self.election
        ctxt['choices'] = list(self.election.option_set.all())
        random.shuffle(ctxt['choices'])
        return ctxt

vote/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  {% comment %}
    THIS IS NEVER USED DIRECTLY.
    So all scripts should instead be added in addnavbar, the next template up,
    using the topscripts and bottomscripts blocks.
    This defines the global grid format - a col3 sidebar, and a col9 body.
  {% endcomment %}

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="{% static "favicon.ico" %}" type="image/x-icon">
  <link rel="shortcut" href="{% static "favicon.ico" %}" type="image/x-icon">
  <link rel="apple-touch-icon" href="{% static "WebLogo.png" %}">

  <title>{% block title %}{% endblock %} - Warwick Tabletop Games and Role-Playing Society</title>

  {% block bootstrap %}
    <link rel="stylesheet" href="{% static "tgrsite_bootstrap.css" %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
          crossorigin="anonymous">
  {% endblock %}

  {% comment %} For scripts we don't want at the top of the email. {% endcomment %}
  {% block topscripts %}
  {% endblock %}

  {% block head %}
    {{ block.super }}
    {# Add some SEO metadata to help discoverability #}
    <meta name="robots" content="noindex">
  {% endblock %}

  {% block css %}
    <link rel="stylesheet" href="{% static "tgrsite_local.css" %}">
    {% comment %}
            This is where a page's custom CSS will go, or a link to the relevant stylesheet I guess.
        {% endcomment %}
  {% endblock %}

</head>

<body>
<div id="pagetop" class="bg-dark">
  <div class="sticky-top">
    {% if debug %}
      <div class="container-fluid align-content-center mb-0" style="background: darkred"><p
        class="text-center text-light font-weight-bolder mb-0">DEBUG</p></div>
    {% endif %}
    <nav class="navbar navbar-dark bg-secondary mb-3">
      <p class="d-flex flex-row justify-content-center w-100 mb-0">
        <a class="" href="/"><img src="{% static "LogoText.png" %}" height="120"
                                  alt="Warwick Tabletop Games and Role-Playing Society"></a>

      </p>
    </nav>
  </div>


  <div class="container-fluid">
    {% block mainbody %}
      <div class="row mb-3">
        <div class="col-xl-2 col-1">
        </div>
        <div class="col-xl-8 col-10">
          <div class="card">
            {% block content %}
            {% endblock %}
          </div>
        </div>
        <div class="col-xl-2 col-1">
        </div>
      </div>
    {% endblock %}
  </div>
</div>

{% comment %} For scripts at the bottom of the page. {% endcomment %}
{% block bottomscripts %}
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"
          integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
          integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
          crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
          integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
          crossorigin="anonymous"></script>
{% endblock %}
</body>
</html>

vote/templates/done.html
{% extends "base.html" %}
{% block title %}Vote Details{% endblock %}
{% block content %}
  <h3 class="card-header">Warwick Tabletop Elections</h3>
  <div class="card-body">
    <p class="card-text">Congratulations, your vote has been cast!</p>
    <p><strong>Source IP:</strong> {{ object.ip }}</p>
    <p><strong>Date/time:</strong> {{ object.time }}</p>
    <h4>Selections:</h4>

    <ul class="list-group">
    {% for i in object.selections.all %}
      <li class="list-group-item">{{ i.text }}</li>
    {% endfor %}
    </ul>
  </div>
{% endblock %}

vote/templates/home.html
{% extends "base.html" %}
{% block title %}Warwick Tabletop Elections{% endblock %}
{% block content %}
  <h3 class="card-header">Warwick Tabletop Elections</h3>
  <div class="card-body">
    <p class="card-text">Please select an election to vote in.</p>
    {% for i in elections %}
      <div class="list-group">
        <a class="list-group-item list-group-item-action" href="{% url "vote:vote" id=i.id %}">{{ i.name }}</a>
      </div>
    {% endfor %}
  </div>
{% endblock %}

vote/templates/results.html
{% extends "base.html" %}
{% load static %}
{% block title %}Results{% endblock %}
{% block css %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static "election.css" %}">
{% endblock %}

{% block content %}
  <h1 class="card-header text-center">{{ election.name }}</h1>
  <div class="card-body">

    <div class="gallery">
      {% for choice in choices %}
        <div class="option">
          <img src="{{ choice.image.url }}" alt="{{ choice.text }}" class="img-thumbnail option-pick">
          <span class="text-center option-text">{{ choice.text }}: {{ choice.votes }}</span>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

vote/templates/votescreen.html
{% extends "base.html" %}
{% load static %}
{% block title %}Vote: {{ election.name }}{% endblock %}
{% block css %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static "election.css" %}">
{% endblock %}

{% block content %}
  <h1 class="card-header text-center">{{ election.name }}</h1>
  <div class="card-body">
    {% if election.intro %}
      <div class="mb-3">
        {{ election.intro|safe }}
      </div>
    {% endif %}
    {% if election.max_votes != 0 %}
      {% if election.max_votes == 1 %}
        <div class="alert alert-info">Please select a single option.</div>
      {% else %}
        <div class="alert alert-info">Please select up to {{ election.max_votes }} options.</div>
      {% endif %}
    {% endif %}
    {% if errors %}
      {% for e in errors %}
        <div class="alert alert-danger">{{ e }}</div>
      {% endfor %}
    {% endif %}
    <form method="post">
      {% csrf_token %}
      <div class="gallery">
        {% for choice in choices %}
          <input type="checkbox" class="d-none" name="selection" id="{{ choice.formid }}"
                 value="{{ choice.id }}">
          <label class="option" for="{{ choice.formid }}">
            <img src="{{ choice.image.url }}" alt="{{ choice.text }}" class="img-thumbnail option-pick">
            <span class="text-center option-text">{{ choice.text }}</span>
          </label>
        {% endfor %}
      </div>
      <button class="btn-outline-primary btn-block btn" type="submit">Submit Vote</button>
    </form>
  </div>
{% endblock %}